version: '3'
services:
  web: 
    build: .
    command: sh -c "sleep 20s ; python3 ./app.py"
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: authapp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysqlvol:/var/lib/mysql
volumes:
  mysqlvol: