"""reset database

Revision ID: 3313d1e97ecf
Revises: 
Create Date: 2025-04-14 18:31:09.957581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3313d1e97ecf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index('user_email')

    op.drop_table('requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_index('email')
        batch_op.create_unique_constraint(None, ['azure_id'])
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')
        batch_op.drop_column('role')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=50), server_default=sa.text("'user'"), nullable=True))
        batch_op.add_column(sa.Column('access_token', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('firstName', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('lastName', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('name')

    op.create_table('requests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('rType', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('user_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('signature', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name='requests_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index('user_email', ['user_email'], unique=True)

    # ### end Alembic commands ###
