"""add approver_id to requests

Revision ID: e0f1ac3d08c3
Revises: 
Create Date: 2025-04-21 20:39:47.921990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f1ac3d08c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_approver_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_unit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'organizational_units', ['current_unit_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['current_approver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_unit_id')
        batch_op.drop_column('current_approver_id')

    # ### end Alembic commands ###
